### ISSUE TITLE
Icon is blurry

### ISSUE THREAD

**Issue by es20490446e** [AXeL-dev/easy-image-downloader#1]
Great addon!

I liked to suggest that the icon is optimized to look sharper, cause right now it looks extremely blurry.

![Screenshot_20210223_081443](https://user-images.githubusercontent.com/9594332/108812335-38f15a00-75af-11eb-9e4f-02b67c0d26d1.png)

**Comment by AXeL-dev** [comment]
Hey,

Thanks for the suggestion! Which version of Firefox are you using?

**Comment by es20490446e** [comment]
85.0.2.

**Comment by es20490446e** [comment]
When resizing icons to the lowest resolutions usually it's necessary to apply a sharpen filter.

But perhaps Firefox supports vector graphics, and it can do the resizing by itself.

If that's the case perhaps we could just borrow an [icon from the Noun Project](https://thenounproject.com/search/?q=download+photo).

**Comment by AXeL-dev** [comment]
Thanks @es20490446e, i'll try to fix that as soon as i can, if you can do a pull request this would be really great!

**Comment by es20490446e** [comment]
https://github.com/AXeL-dev/easy-image-downloader/pull/3
